# This is a basic workflow that is manually triggered

name: Mirror public whitelists

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: "actions/checkout@v4.1.2"
    - name: set email
      run: git config --global user.email "action@example.com"
    - name: set name
      run: git config --global user.name "Github Action"
    - name: set rebase
      run: git config pull.rebase true
    - name: checkout dev
      run: git checkout -b dev
    - name: remove files
      run: for FILE in $(ls); do if [ -d "${FILE}" ]; then git rm -r $FILE; elif [ -f "${FILE}" ]; then git rm $FILE; fi; done
    - name: push dev
      run: git push --set-upstream origin dev
    - name: clone public branch
      run: git remote add -t public other-repo https://oauth2:{{MIRROR_TOKEN}}@gitlab.gwdg.de/loosolab/software/metadata_whitelists.git
    - name: update
      run: git remote update
    - name: checkout dev
      run: git checkout dev
    - name: pull
      run: git pull origin dev
    - name: merge
      run: git merge --allow-unrelated-histories --strategy-option=theirs other-repo/public
    - name: push
      run: git push 
    - name: checkout main
      run: git checkout main
    - name: merge main
      run: git merge --allow-unrelated-histories --strategy-option=theirs origin/dev
    - name: push main
      run: git push --set-upstream origin main
    - name: fetch
      run: git fetch --all --prune
    - name: get heads
      run: lines=$(git for-each-ref refs/heads/ --format='%(refname:short)')
    - name: remove local
      run: if [ $(echo $lines | grep -w dev | wc -l) -gt 0 ]; then git branch -D dev; echo "delete local branch"; else echo "No local dev branch to delete"; fi
    - name: fetch
      run: git fetch --all --prune
    - name: get remotes
      run: lines=$(git for-each-ref refs/remotes/ --format='%(refname:short)')
    - name: remove remote
      run: if [ $(echo $lines | grep -w dev | wc -l) -gt 0 ]; then git push origin --delete dev; echo "delete local branch"; else echo "No local dev branch to delete"; fi

